---
- name: Install and configure EAP cluster
  hosts: eap
  become: true
  collections:
    - redhat.eap
  vars_files:
    - vars.yml
  pre_tasks:
    - name: Create cluster node list
      ansible.builtin.set_fact:
        eap_cluster_nodes: >
          {{ eap_cluster_nodes | default([]) + [
               {
                 "name": item,
                 "address": 'jgroups-' + item,
                 "inventory_host": hostvars[item].ansible_default_ipv4.address | default(item) + '[7600]',
                 "value": hostvars[item].ansible_default_ipv4.address | default(item)
               }
             ] }}
      loop: "{{ ansible_play_batch }}"
  roles:
    - eap_install
    - eap_systemd

- name: Verify EAP installation
  ansible.builtin.import_playbook: validate.yml

- name: Deploy demo application
  hosts: eap
  become: true
  collections:
    - redhat.eap
  vars_files:
    - vars.yml
  vars:
    eap_app_deployment_file: "/tmp/{{ app.name }}"
    eap_app_deploy_name: "{{ app.name }}"
    jboss_cli_controller_host: "127.0.0.1"
    jboss_cli_controller_port: "9990"
    eap_apps_jboss_cli_deploy_force: true
  pre_tasks:
    - name: Download demo app on controller
      ansible.builtin.get_url:
        url: "{{ app.url }}"
        dest: "/tmp/{{ app.name }}"
        mode: "0644"
      delegate_to: localhost
      run_once: true
      become: false
  roles:
    - eap_app_deploy
