---
- name: Upgrade EAP to 8.1.5
  hosts: eap
  become: true
  collections:
    - redhat.eap
  vars:
    eap_version: "8.1.0"
    eap_offline_install: true
    eap_prospero_update: true
  roles:
    - eap_install
    - eap_systemd
  tasks:
    - name: Restart eap service
      ansible.builtin.service:
        name: eap
        state: restarted

- name: Verify upgraded EAP
  ansible.builtin.import_playbook: validate.yml
